/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity2 */

#ifndef _Included_com_example_androidex_MainActivity2
#define _Included_com_example_androidex_MainActivity2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_MainActivity2
 * Method:    read_fpga
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity2_read_1fpga
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity2
 * Method:    write_fpga
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity2_write_1fpga
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_MainActivity2
 * Method:    close_fpga
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity2_close_1fpga
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
